### ISSUE TITLE
GooglePlus badge

### ISSUE THREAD

**Issue by JeanHuit** [GDGGhana/GDGGhana.github.io#1]
Google plus +1 badge atop the page does not correlate to the the number of plus ones on the gdg page.

**Comment by jeffgodwyll** [comment]
:+1:  Yeah I did check up on that but there's no official way to pull that info. http://stackoverflow.com/a/16159280/2295256

Our best bet is to get the domain set up so that all subsequent plus ones get associated with it for life

**Comment by JeanHuit** [comment]
Sorted. Rendered with the follow button. Maybe a little styling will do. :)
