### ISSUE TITLE
Add site url to G+ page

### ISSUE THREAD

**Issue by jeffgodwyll** [GDGGhana/GDGGhana.github.io#4]
2a80ccc9434ad896a0ffecdf3938b0eb8b5c2115 We should add the site url to the [GDG Ghana G+ page](https://plus.google.com/117620641470438104052/about) so that it gets picked up by the GDG global directory

**Comment by jeffgodwyll** [comment]
@JeanHuit

**Comment by JeanHuit** [comment]
Done @jeffgodwyll

**Comment by jeffgodwyll** [comment]
Cool :+1:
